version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: rockai
      MYSQL_USER: rockai_user
      MYSQL_PASSWORD: rockai_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  mariadb_data:
